"""Helpers for generating a local checker environment file."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .config import DEFAULT_MEMORY_GB, DEFAULT_OCPUS, DEFAULT_SHAPE


@dataclass(frozen=True)
class SetupConfig:
    """Values written to a generated .env file."""

    compartment_id: str
    availability_domains: tuple[str, ...]
    shape: str = DEFAULT_SHAPE
    ocpus: float = DEFAULT_OCPUS
    memory_gb: float = DEFAULT_MEMORY_GB
    auth: str = "config"
    config_file: str = "~/.oci/config"
    profile: str = "DEFAULT"
    webhook_url: str | None = None
    notify_on_unavailable: bool = False
    output_json: bool = False
    exit_nonzero_when_unavailable: bool = False


def _format_bool(value: bool) -> str:
    return "true" if value else "false"


def _format_number(value: float) -> str:
    return f"{value:g}"


def render_env(config: SetupConfig) -> str:
    """Render a complete .env file for the checker."""

    lines = [
        "# Generated by: ooc-checker configure",
        "# Root tenancy OCID works for Always Free resources, or use a target compartment OCID.",
        f"OCI_COMPARTMENT_ID={config.compartment_id}",
        "",
        "# Comma-separated AD names exactly as OCI returns them.",
        f"OCI_AVAILABILITY_DOMAINS={','.join(config.availability_domains)}",
        "",
        "# Ampere / Arm Always Free shape and size to check.",
        f"OCI_SHAPE={config.shape}",
        f"OCI_OCPUS={_format_number(config.ocpus)}",
        f"OCI_MEMORY_GB={_format_number(config.memory_gb)}",
        "# OCI_FAULT_DOMAIN=FAULT-DOMAIN-1",
        "",
        "# Authentication: config for ~/.oci/config, or instance_principal when running on OCI.",
        f"OCI_AUTH={config.auth}",
        f"OCI_CONFIG_FILE={config.config_file}",
        f"OCI_PROFILE={config.profile}",
        "",
        "# Optional webhook. Discord webhooks work with content; Slack-compatible webhooks use text.",
    ]
    if config.webhook_url:
        lines.append(f"WEBHOOK_URL={config.webhook_url}")
    else:
        lines.append("# WEBHOOK_URL=https://discord.com/api/webhooks/...")
    lines.extend(
        [
            f"NOTIFY_ON_UNAVAILABLE={_format_bool(config.notify_on_unavailable)}",
            f"OUTPUT_JSON={_format_bool(config.output_json)}",
            f"EXIT_NONZERO_WHEN_UNAVAILABLE={_format_bool(config.exit_nonzero_when_unavailable)}",
            "",
        ]
    )
    return "\n".join(lines)


def discover_from_oci(config_file: str, profile: str) -> tuple[str, tuple[str, ...]]:
    """Discover tenancy OCID and availability domains using an OCI config profile."""

    import oci

    expanded_config_file = str(Path(config_file).expanduser())
    sdk_config = oci.config.from_file(file_location=expanded_config_file, profile_name=profile)
    oci.config.validate_config(sdk_config)
    tenancy_id = sdk_config["tenancy"]
    identity_client = oci.identity.IdentityClient(sdk_config)
    response = identity_client.list_availability_domains(compartment_id=tenancy_id)
    availability_domains = tuple(domain.name for domain in response.data)
    return tenancy_id, availability_domains


def write_env_file(path: str | Path, config: SetupConfig, overwrite: bool = False) -> Path:
    """Write the generated .env file."""

    destination = Path(path)
    if destination.exists() and not overwrite:
        raise FileExistsError(f"{destination} already exists. Pass --force to overwrite it.")
    destination.write_text(render_env(config), encoding="utf-8")
    return destination
